@startuml

class Main
'##########################################
package Components {
    note "Components are not allowed to have any dependencies." as N2
    class AssetComponents
    class BulletComponents
    class CameraComponents
    class EnemyComponents
    class GenericComponents
    class LevelComponents
    class PlayerComponents
    class PhysicsComponents
    class WallComponents
}
Systems <-- Components
'##########################################
package Events {
    note "Events are not allowed to have any dependencies." as N3
    class BulletEvents
    class EnemySpawnEvents
}

Plugins <- Events
Systems <- Events
'##########################################
package Plugins {
    class HeadBoxPlugin
    class MainMenuPlugin
    class GamePlugin
}
Main <-- HeadBoxPlugin
HeadBoxPlugin <-- MainMenuPlugin
HeadBoxPlugin <-- GamePlugin
'##########################################
package States {
    note "States are not allowed to have any dependencies." as N5
    class ScreenState
}
Plugins <- States
Systems <- States
'##########################################
package Systems {
    note "Systems are not allowed to have hard dependencies on each other." as N1
    class ArenaSystems
    class AssetSystems
    class BulletSystems
    class CameraSystems
    class CollisionSystems
    class EnemySystems
    class GenericSystems
    class LevelSystems
    class PlayerSystems
}
Plugins <---- Systems
'##########################################
package Utils {
    note "Utils are not allowed to have any dependencies." as N4
    class GenericConstants
    class PhysicsConstants
}
Plugins <- Utils
Systems <- Utils
'##########################################


@enduml