@startuml
class Main
class HeadBoxPlugin
class MainMenuPlugin
class GamePlugin


package Generic {
    note "The generic classes should not use any crates" as N1
    class Dataclasses
    class DisplayHandler
}

package Systems {
    class PlayerSystems
    class BulletSystems
    class EnemySystems
    class CollisionSystems
    class LevelSystems
    class RigidBodySystems
    class ArenaSystems
}

package DataLayer {
    class PlayerBundle
    class BulletBundle
    class ZombieBundle
    class WallBundle
    class LevelBundle
    class RigidBodyBundle

}
Main <-- HeadBoxPlugin

HeadBoxPlugin <-- MainMenuPlugin
HeadBoxPlugin <-- GamePlugin

GamePlugin <-- PlayerSystems
GamePlugin <-- BulletSystems
GamePlugin <-- EnemySystems
GamePlugin <-- CollisionSystems
GamePlugin <-- LevelSystems
GamePlugin <-- RigidBodySystems
GamePlugin <-- ArenaSystems

PlayerSystems <-- PlayerBundle
PlayerSystems <-- BulletBundle
EnemySystems <-- ZombieBundle
ArenaSystems <-- WallBundle
LevelSystems <-- LevelBundle
LevelSystems <-- EnemySystems


WallBundle <|-- RigidBodyBundle
ZombieBundle <|-- RigidBodyBundle
BulletBundle <|-- RigidBodyBundle
PlayerBundle <|-- RigidBodyBundle

@enduml