@startuml
class Main
class HeadBoxPlugin
class DisplayHandler
class MainMenuPlugin
class GamePlugin


package Generic {
    class GenericFunctions
}

package player {
    class PlayerSystems
    class PlayerBundle
}

package Bullet {
    class BulletBundle
}

package Enemies {
    class EnemySystems
    class ZombieBundle
}
package Movement {
    class MovementSystems
}


Main <-- HeadBoxPlugin

HeadBoxPlugin <-- MainMenuPlugin
HeadBoxPlugin <-- GamePlugin
HeadBoxPlugin <-- DisplayHandler

MainMenuPlugin <- DisplayHandler

GamePlugin <-- PlayerSystems
PlayerSystems <-- PlayerBundle


PlayerSystems <-- BulletBundle

GamePlugin <-- EnemySystems
EnemySystems <-- ZombieBundle

GamePlugin <-- MovementSystems
@enduml